ignore:
  - "services/backend/db/**"
  - "services/backend/src/test/**"
  - "services/backend/src/main/java/**/entity/**"
  - "services/backend/src/main/java/**/cli/**"
  - "services/backend/src/main/java/**/dto/**"
  - "services/backend/src/main/java/**/config/**"
  - "services/backend/src/main/java/**/repository/**"
  - "services/backend/src/main/java/**/exception/**"
  - "services/backend/src/main/java/**/helper/**"
  - "services/backend/src/main/java/**/generated/**"
  - "services/backend/src/main/java/**/migration/**"
  - "services/backend/src/main/java/**/*Application.java"
  - "services/backend/src/main/java/**/*Config.java"
  - "services/backend/src/main/java/**/*Configuration.java"
  - "services/backend/src/main/resources/db/**"


  - "services/frontend/src/types/**"
  - "services/frontend/env.d.ts"
  - "services/frontend/src/**/__mocks__/**"
  - "services/frontend/src/**/__tests__/**"
  - "services/frontend/src/firebase.ts"
  - "services/frontend/e2e/**"
  - "services/frontend/src/main.ts"
  - "services/frontend/vite.config.ts"
  - "services/frontend/vitest.config.ts"
  - "services/frontend/playwright.config.ts"
  - "services/frontend/postcss.config.js"
  - "services/frontend/public/**"
  - "services/frontend/index.html"
  - "services/frontend/src/assets/**"
  - "services/frontend/src/assets/styles/**"
  - "services/frontend/src/plugins/**"
  - "services/frontend/src/validation/**"
  - "services/frontend/src/router/**"
  - "services/frontend/src/services/**"
  - "services/frontend/src/stores/**"

  - "services/backoffice/public/**"
  - "services/backoffice/angular.json"
  - "services/backoffice/karma.conf.js"
  - "services/backoffice/tsconfig.json"
  - "services/backoffice/tsconfig.app.json"
  - "services/backoffice/tsconfig.spec.json"
  - "services/backoffice/src/environments/**"
  - "services/backoffice/src/main.ts"
  - "services/backoffice/src/index.html"
  - "services/backoffice/src/styles.scss"

  - "services/analytics/tests/**"

