ignore:
  - "backend/db/**"
  - "backend/src/test/**"
  - "backend/src/main/java/**/entity/**"
  - "backend/src/main/java/**/cli/**"
  - "backend/src/main/java/**/dto/**"
  - "backend/src/main/java/**/config/**"
  - "backend/src/main/java/**/repository/**"
  - "backend/src/main/java/**/exception/**"
  - "backend/src/main/java/**/helper/**"
  - "backend/src/main/java/**/generated/**"
  - "backend/src/main/java/**/migration/**"
  - "backend/src/main/java/**/*Application.java"
  - "backend/src/main/java/**/*Config.java"
  - "backend/src/main/java/**/*Configuration.java"
  - "backend/src/main/resources/db/**"


  - "frontend/src/types/**"
  - "frontend/env.d.ts"
  - "frontend/src/**/__mocks__/**"
  - "frontend/src/**/__tests__/**"
  - "frontend/src/firebase.ts"
  - "frontend/e2e/**"
  - "frontend/src/main.ts"
  - "frontend/vite.config.ts"
  - "frontend/vitest.config.ts"
  - "frontend/playwright.config.ts"
  - "frontend/postcss.config.js"
  - "frontend/public/**"
  - "frontend/index.html"
  - "frontend/src/assets/**"
  - "frontend/src/assets/styles/**"
  - "frontend/src/plugins/**"
  - "frontend/src/validation/**"
  - "frontend/src/router/**"
  - "frontend/src/services/**"
  - "frontend/src/stores/**"
