CREATE TABLE public.surveys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    title VARCHAR(255) NOT NULL
);

CREATE TABLE public.questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position INTEGER NOT NULL,
    question_text VARCHAR(255) NOT NULL UNIQUE,
    survey_id BIGINT,
    CONSTRAINT fknf38uiy78c0g0tmo68btk3y0p FOREIGN KEY (survey_id) REFERENCES public.surveys(id)
);

CREATE TABLE public.responses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submitted_at TIMESTAMP,
    survey_id BIGINT,
    CONSTRAINT fkemug20qu5fygiy69wj7sel8hc FOREIGN KEY (survey_id) REFERENCES public.surveys(id)
);

CREATE TABLE public.answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    answer VARCHAR(255),
    question_id BIGINT,
    response_id BIGINT,
    CONSTRAINT answers_answer_check CHECK (
        answer IN (
            'TOTALLY_DISAGREE',
            'DISAGREE',
            'NEUTRAL',
            'AGREE',
            'FULLY_AGREE'
        )
    ),
    CONSTRAINT fk3erw1a3t0r78st8ty27x6v3g1 FOREIGN KEY (question_id) REFERENCES public.questions(id),
    CONSTRAINT fkdvrc91061f1tdfkl8wv77k4t3 FOREIGN KEY (response_id) REFERENCES public.responses(id)
);
