ALTER TABLE users ADD COLUMN survey_credits INT NOT NULL DEFAULT 0;

CREATE TABLE payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stripe_session_id      TEXT UNIQUE NOT NULL,       -- Ties to Checkout session
  stripe_payment_intent  TEXT,                       -- For refunds, disputes
  user_id                BIGINT REFERENCES users(id) ON DELETE SET NULL,
  email                  TEXT,                       -- Captured from Checkout, for support
  amount_cents           INT NOT NULL,
  currency               TEXT NOT NULL DEFAULT 'eur',
  credits_granted        INT NOT NULL DEFAULT 1,
  status                 TEXT NOT NULL,              -- PENDING / PAID / FAILED / REFUNDED / DISPUTED
  failure_reason         TEXT,
  stripe_event_id        TEXT,                       -- Last processed Stripe event (dedupes)
  created_at             TIMESTAMP DEFAULT now(),
  updated_at             TIMESTAMP DEFAULT now()
);

CREATE TABLE payment_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_id BIGINT REFERENCES payments(id),
  event_type TEXT,
  stripe_event_id TEXT,
  status TEXT,
  received_at TIMESTAMP DEFAULT now()
);