services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
      - ../../services/backend/db/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
    ports:
      - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.4
    container_name: logstash
    ports:
      - "5000:5000"
    environment:
      # DO NOT USE QUOTES they will be passed as characters in the url
      - ELASTIC_SEARCH_URL=http://elasticsearch:9200
      - ENVIRONMENT=development
    volumes:
      - ../elk/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS="http://elasticsearch:9200"
      - ELASTICSEARCH_USERNAME=admin
      - ELASTICSEARCH_PASSWORD=secret
    depends_on:
      - elasticsearch

  rabbitmq:
    image: rabbitmq:3.13-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"

  patronx-worker:
    image: xdanielsb/patronx:2.0.0
    entrypoint: ["remoulade"]
    command: ["patronx.tasks"]
    restart: unless-stopped
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq:5672/
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      BACKUP_DIR: '/app/backups'
      S3_BUCKET: ${S3_BUCKET}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_REGION}
    volumes:
      - ../../backups:/app/backups
    depends_on:
      - db
      - rabbitmq

  analytics:
    build:
      context: ../services/analytics
      network: host
    container_name: ai-analytics
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_MODEL=llama3
      - SENTRY_AUTH_DSN=${SENTRY_AUTH_DSN}
    depends_on:
      - ollama
      - logstash

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    healthcheck:
      # sends nothing to cat, cat sends nothing to the port just to cheeck connection
      test: "bash -c 'cat < /dev/null > /dev/tcp/localhost/11434'"
      interval: 10s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    command: > 
      start-dev
      --import-realm
      --spi-admin-allowed-system-variables=DOMAIN_URL,KC_CLIENT_PROD_BACKEND_SECRET,KC_CLIENT_STAGING_BACKEND_SECRET,GOOGLE_CLIENT_ID_PROD,GOOGLE_CLIENT_SECRET_PROD,GOOGLE_CLIENT_ID_STAGING,GOOGLE_CLIENT_SECRET_STAGING
    container_name: keycloak
    environment:
      DOMAIN_URL: ${DOMAIN_URL}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: secret
      KC_CLIENT_STAGING_BACKEND_SECRET: ${KC_CLIENT_STAGING_BACKEND_SECRET}
      KC_CLIENT_PROD_BACKEND_SECRET: ${KC_CLIENT_PROD_BACKEND_SECRET}
      GOOGLE_CLIENT_ID_STAGING: ${GOOGLE_CLIENT_ID_STAGING}
      GOOGLE_CLIENT_SECRET_STAGING: ${GOOGLE_CLIENT_SECRET_STAGING}
      GOOGLE_CLIENT_ID_PROD: ${GOOGLE_CLIENT_ID_PROD}
      GOOGLE_CLIENT_SECRET_PROD: ${GOOGLE_CLIENT_SECRET_PROD}
    volumes:
      - ../keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8082:8080"

volumes:
  db-data:
  pgadmin-data:
  ollama-data:

