services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
      - ../../backups:/backups
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  caddy:
    image: caddy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./CaddyfileKeycloak:/etc/caddy/Caddyfile
      - caddy-data:/data
    depends_on:
      - keycloak
    healthcheck:
      test: "bash -c 'cat < /dev/null > /dev/tcp/localhost/80'"
      interval: 10s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:4.1.1-management
    ports: [ "5672:5672", "15672:15672" ]
    healthcheck:
      test: "bash -c 'cat < /dev/null > /dev/tcp/localhost/5672'"
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 10

  patronx-worker:
    image: xdanielsb/patronx:2.2.0
    entrypoint: ["patronx"]
    command: ["start"]
    restart: unless-stopped
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq:5672/
      REDIS_URL: redis://redis:6379/0
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      BACKUP_DIR: /app/backups
      S3_BUCKET: ${S3_BUCKET}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_REGION}
      BACKUP_CRON: "0 */12 * * *"     # Every 12 hours at minute 0 (e.g., 00:00, 12:00)
      CLEANUP_CRON: "0 3 * * *"       # Once daily at 3:00 AM
    volumes:
      - ../../backups:/app/backups
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy


  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    command: >
      start
      --import-realm
      --http-enabled=true
      --hostname-strict=false
      --proxy-headers xforwarded
      --spi-admin-allowed-system-variables=DOMAIN_URL,KC_CLIENT_PROD_BACKEND_SECRET,KC_CLIENT_STAGING_BACKEND_SECRET,GOOGLE_CLIENT_ID_PROD,GOOGLE_CLIENT_SECRET_PROD,GOOGLE_CLIENT_ID_STAGING,GOOGLE_CLIENT_SECRET_STAGING
    container_name: keycloak
    environment:
      DOMAIN_URL: ${DOMAIN_URL}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_CLIENT_STAGING_BACKEND_SECRET: ${KC_CLIENT_STAGING_BACKEND_SECRET}
      KC_CLIENT_PROD_BACKEND_SECRET: ${KC_CLIENT_PROD_BACKEND_SECRET}
      GOOGLE_CLIENT_ID_STAGING: ${GOOGLE_CLIENT_ID_STAGING}
      GOOGLE_CLIENT_SECRET_STAGING: ${GOOGLE_CLIENT_SECRET_STAGING}
      GOOGLE_CLIENT_ID_PROD: ${GOOGLE_CLIENT_ID_PROD}
      GOOGLE_CLIENT_SECRET_PROD: ${GOOGLE_CLIENT_SECRET_PROD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ../keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
      - ../keycloak/user-profile.json:/opt/keycloak/data/import/user-profile.json
    depends_on:
      - db
    healthcheck:
      test: "bash -c 'cat < /dev/null > /dev/tcp/localhost/8080'"
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  db-data:
  caddy-data:

