services:
  db:
    image: postgres:17.5
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
      - ../../services/backend/db/init:/docker-entrypoint-initdb.d
      - ../../backups:/backups
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - es-data:/usr/share/elasticsearch/data
    healthcheck:
      test: "bash -c 'cat < /dev/null > /dev/tcp/localhost/9200'"
      interval: 10s
      timeout: 5s
      retries: 10

  logstash:
    image: docker.elastic.co/logstash/logstash:9.0.3
    container_name: logstash
    environment:
      - ELASTIC_SEARCH_URL=${ELASTIC_SEARCH_URL}
      - ENVIRONMENT=${ENVIRONMENT}
    volumes:
      - ../elk/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    healthcheck:
      test: "bash -c 'cat < /dev/null > /dev/tcp/localhost/5000'"
      interval: 10s
      timeout: 5s
      retries: 10

  kibana:
    image: docker.elastic.co/kibana/kibana:9.0.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTIC_SEARCH_URL}
      - SERVER_BASEPATH=/monitoring
      - SERVER_REWRITEBASEPATH=true
    depends_on:
      - elasticsearch
    healthcheck:
      test: "bash -c 'cat < /dev/null > /dev/tcp/localhost/5601'"
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ../../services/backend
      network: "host"
    container_name: survey-backend
    restart: always
    depends_on:
      - db
      - logstash
      - analytics
    environment:
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - STRIPE_PRICE_ID=${STRIPE_PRICE_ID}
      - STRIPE_FRONTEND_URL=${STRIPE_FRONTEND_URL}
      - SPRING_DATASOURCE_URL=${POSTGRES_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - LOGSTASH_HOST=logstash
      - LOGSTASH_PORT=5000
      - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
      - SENTRY_AUTH_DSN=${SENTRY_AUTH_DSN}
      - ANALYTICS_URL=${ANALYTICS_URL}  
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - SENDGRID_FROM_EMAIL=${SENDGRID_FROM_EMAIL}
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - INVOICE_STORAGE_PATH=./invoices
      - COMPANY_NAME=${COMPANY_NAME}
      - COMPANY_WEBSITE=${COMPANY_WEBSITE}
      - COMPANY_LOGO_URL=${COMPANY_LOGO_URL}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:8080/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    volumes:
      - ../../invoices:/app/invoices

  frontend:
    build:
      context: ../../services/frontend
      network: "host"
      args:
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
        VITE_STRIPE_PUBLISHABLE_KEY: ${VITE_STRIPE_PUBLISHABLE_KEY}
        VITE_GOOGLE_WEB_CLIENT_ID: ${VITE_GOOGLE_WEB_CLIENT_ID}
        VITE_KEYCLOAK_URL: ${KEYCLOAK_URL}
        VITE_KEYCLOAK_REALM: ${KEYCLOAK_REALM}
        SENTRY_AUTH_DSN: ${SENTRY_AUTH_DSN}
    container_name: survey-frontend
    restart: always
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD-SHELL", "netstat -tulpn | grep -q ':5173 .*LISTEN'"]
      interval: 10s
      timeout: 5s
      retries: 10

  caddy:
    image: caddy:2.10.0-alpine
    ports:
      - "80:80"
      - "443:443"
    environment:
      - KIBANA_USER=${KIBANA_USER}
      - KIBANA_PASS_HASH=${KIBANA_PASS_HASH}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
    depends_on:
      - frontend
    healthcheck:
      test: ["CMD-SHELL", "netstat -tulpn | grep -q ':443 .*LISTEN'"]
      interval: 10s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:4.1.1-management
    ports: [ "5672:5672", "15672:15672" ]
    healthcheck:
      test: "bash -c 'cat < /dev/null > /dev/tcp/localhost/5672'"
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:8.0.2-alpine
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 10

  patronx-worker:
    image: xdanielsb/patronx:2.2.0
    entrypoint: ["patronx"]
    command: ["start"]
    restart: unless-stopped
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq:5672/
      REDIS_URL: redis://redis:6379/0
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      BACKUP_DIR: /app/backups
      S3_BUCKET: ${S3_BUCKET}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_REGION}
      BACKUP_CRON: "0 */12 * * *"
      CLEANUP_CRON: "0 3 * * *"
    volumes:
      - ../../backups:/app/backups
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:v3.4.2
    container_name: prometheus
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - node-exporter
    healthcheck:
      test: ["CMD-SHELL", "netstat -tulpn | grep -q ':9090 .*LISTEN'"]
      interval: 10s
      timeout: 5s
      retries: 10


  grafana:
    image: grafana/grafana:12.0.2
    container_name: grafana
    volumes:
      - ../monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ../monitoring/grafana/provisioning/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    depends_on:
      - prometheus
    healthcheck:
      test: "bash -c 'cat < /dev/null > /dev/tcp/localhost/3000'"
      interval: 10s
      timeout: 5s
      retries: 10



  node-exporter:
    image: prom/node-exporter:v1.9.1
    container_name: node-exporter
    command:
      - '--path.rootfs=/host'
    volumes:
      - '/:/host:ro,rslave'
    healthcheck:
      test: ["CMD-SHELL", "netstat -tulpn | grep -q ':9100 .*LISTEN'"]
      interval: 10s
      timeout: 5s
      retries: 10


  analytics:
    build:
      context: ../../services/analytics
      network: "host"
    container_name: ai-analytics
    environment:
      - OLLAMA_URL=${OLLAMA_URL}
      - OLLAMA_MODEL=${OLLAMA_MODEL}
      - SENTRY_AUTH_DSN=${SENTRY_AUTH_DSN}
    depends_on:
      - ollama
    healthcheck:
      test: "bash -c 'cat < /dev/null > /dev/tcp/localhost/8000'"
      interval: 10s
      timeout: 5s
      retries: 10



  ollama:
    image: ollama/ollama:0.1.39
    container_name: ollama
    volumes:
      - ollama-data:/root/.ollama
    healthcheck:
      test: "bash -c 'cat < /dev/null > /dev/tcp/localhost/11434'"
      interval: 10s
      retries: 5

  backoffice:
    build:
      context: ../../services/backoffice
      network: "host"
    container_name: survey-backoffice
    restart: always
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - SENTRY_AUTH_DSN=${SENTRY_AUTH_DSN}
    healthcheck:
      test: ["CMD-SHELL", "netstat -tulpn | grep -q ':4200 .*LISTEN'"]
      interval: 10s
      timeout: 5s
      retries: 10


volumes:
  db-data:
  caddy-data:
  es-data:
  prometheus_data:
  ollama-data:
  invoices:
