# These will be overridden by Testcontainers
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true

sentry.dsn=
sentry.traces-sample-rate=0.0
sentry.enabled=false