name: Deploy keycloak

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: keycloak
    concurrency:
      group: deploy-keycloak-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy keycloak resources to production server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "infra/keycloak/,infra/scripts/,Makefile,makefiles/keycloak.mk"
          target: "/home/deploy/survey-app"
          strip_components: 0
          rm: false
          overwrite: true

      - name: Upload .env file
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cat << 'EOF' > /home/deploy/survey-app/infra/keycloak/.env
              ${{ secrets.ENV_FILE }}
            EOF

      - name: Upload keycloak custom realm configuration
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cat << 'EOF' > /home/deploy/survey-app/infra/keycloak/realm-export.json
              ${{ secrets.REALM_EXPORT }}
            EOF

      - name: Upload Caddyfile
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cat << 'EOF' > /home/deploy/survey-app/infra/keycloak/Caddyfile
              ${{ secrets.CADDYFILE_KEYCLOAK }}
            EOF

      - name: Deploy with Docker Compose (Production)
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/deploy/survey-app
            docker compose -f infra/keycloak/docker-compose.yml down --remove-orphans
            docker compose -f infra/keycloak/docker-compose.yml --env-file infra/keycloak/.env up -d --build
