name: Deploy to monitoring

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: monitoring
    concurrency:
      group: deploy-monitoring-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy project files to production server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "infra/monitoring/,infra/scripts/,Makefile,makefiles/monitoring.mk"
          target: "/home/deploy/survey-app"
          strip_components: 0
          rm: false
          overwrite: true

      - name: Upload .env file
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cat << 'EOF' > /home/deploy/survey-app/infra/monitoring/.env
              ${{ secrets.ENV_FILE }}
            EOF

      - name: Upload Caddyfile
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cat << 'EOF' > /home/deploy/survey-app/infra/monitoring/Caddyfile
              ${{ secrets.CADDY_FILE }}
            EOF

      - name: Upload Prometheus config
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cat << 'EOF' > /home/deploy/survey-app/infra/monitoring/prometheus.yml
              ${{ secrets.PROMETHEUS_FILE }}
            EOF

      - name: Deploy with Docker Compose
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/deploy/survey-app
            docker compose -f infra/monitoring/docker-compose.yml down --remove-orphans
            docker compose -f infra/monitoring/docker-compose.yml --env-file infra/monitoring/.env up -d --build
