name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: deploy-prod-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy project files to production server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/home/deploy/survey-app"
          strip_components: 0
          rm: false
          overwrite: true

      - name: Upload .env file
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cat << 'EOF' > /home/deploy/survey-app/infra/compose/.env
              ${{ secrets.ENV_FILE }}
            EOF

      - name: Upload Caddyfile
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cat << 'EOF' > /home/deploy/survey-app/infra/compose/Caddyfile
              ${{ secrets.CADDY_FILE }}
            EOF

      - name: Upload Env Configuration Backoffice
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cat << 'EOF' > /home/deploy/survey-app/services/backoffice/src/environments/environment.ts
              ${{ secrets.BACKOFFICE_ENVIROMENT_TS }}
            EOF

      - name: Deploy with Docker Compose (Production)
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/deploy/survey-app
            docker compose -f infra/compose/docker-compose.yml down
            docker compose -f infra/compose/docker-compose.yml --env-file infra/compose/.env up -d --build
