
name: Deploy to staging

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    concurrency:
      group: deploy-staging-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy project files to production server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/root/survey-app"
          strip_components: 0
          rm: false
          overwrite: true

      - name: Upload .env file
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cat << 'EOF' > /root/survey-app/infra/compose/.env
              ${{ secrets.ENV_FILE }}
            EOF

      - name: Upload Caddyfile
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cat << 'EOF' > /root/survey-app/infra/compose/Caddyfile
              ${{ secrets.CADDY_FILE }}
            EOF

      - name: Upload Env Configuration Backoffice
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cat << 'EOF' > /root/survey-app/services/backoffice/src/environments/environment.ts
              ${{ secrets.BACKOFFICE_ENVIROMENT_TS }}
            EOF

      - name: Deploy with Docker Compose
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/survey-app
            docker compose -f infra/compose/docker-compose.yml down
            docker compose -f infra/compose/docker-compose.yml --env-file infra/compose/.env up -d --build
