
name: Backend CI

on:
  push:
    paths:
      - 'services/backend/**'
      - '.github/workflows/ci-backend.yml'
    branches: [ master ]
  pull_request:
    paths:
      - 'services/backend/**'
      - '.github/workflows/ci-backend.yml'
    branches: [ master ]

jobs:
  backend-tests:
    name: Run Spring Boot Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run backend tests
        run: ./mvnw clean verify

      - name: Check code format with Spotless
        run: ./mvnw spotless:check
