name: Frontend CI

on:
  push:
    paths:
      - 'services/frontend/**'
      - '.github/workflows/ci-frontend.yml'
    branches: [ master ]
  pull_request:
    paths:
      - 'services/frontend/**'
      - '.github/workflows/ci-frontend.yml'
    branches: [ master ]

jobs:
  frontend-tests:
    name: Run Vue + Vitest Frontend Tests + Linter
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('services/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm install

      - name: Run Vitest
        run: npx vitest run

      - name: Run Linter
        run: npm run lint
