
name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: deploy-prod-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy project files to production server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/root/survey-app"
          strip_components: 0
          rm: false
          overwrite: true

      - name: Upload .env file
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cat << 'EOF' > /root/survey-app/.env
              ${{ secrets.ENV_FILE }}
            EOF

      - name: Upload Caddyfile
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cat << 'EOF' > /root/survey-app/Caddyfile
              ${{ secrets.CADDY_FILE }}
            EOF

      - name: Upload Firebase Service Account
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cat << 'EOF' > /root/survey-app/services/backend/src/main/resources/firebase-service-account.json
             ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
            EOF


      - name: Deploy with Docker Compose (Production)
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/survey-app
            docker compose -f infrastructure/docker-compose.yml down
            docker compose -f infrastructure/docker-compose.yml --env-file .env up -d --build

